version: '2'

services:
  app:
    image: 'mitrasoftserver:latest'
    build:
      context: ./mitrasoft_server
    container_name: mitrasoftserver
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mitrasoftdb:5432/mitrasoftdb
      - SPRING_DATASOURCE_USERNAME=mitrasoftuser
      - SPRING_DATASOURCE_PASSWORD=qwerty

  client:
    image: 'mitrasoft-client:latest'
    build: 
      context: ./mitrasoft_rest_client/
    container_name: mitrasoftclient
    ports:
      - "8081:8081"
    environment:
      - SERVER_URL=http://mitrasoftserver:8080/rest/message


  db:
    image: postgres:13
    container_name: mitrasoftdb
    environment:
      - POSTGRES_DB=mitrasoftdb
      - POSTGRES_USER=mitrasoftuser
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mitrasoftuser -d mitrasoftdb"]
      interval: 5s
      timeout: 5s
      retries: 5 
    
  # liquibase:
  #   image: liquibase/liquibase:4.9
  #   container_name: liquibase
  #   command: --url=jdbc:postgresql://mitrasoft_db:5432/mitrasoft_db?user=mitrasoftuser&password=qwerty --changeLogFile=changelog.xml update
  #   depends_on: 
  #     - db
  #   volumes:
  #     - ./mitrasoft_server/src/main/resources/db/changelog/changelog-master.xml:/liquibase/changelog.xml
